# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Funky-Storage-Memcached
version:      0.03
version_from: lib/Cache/Funky/Storage/Memcached.pm
installdirs:  site
requires:
    Cache::Funky:                  0
    Cache::Funky::Storage:         0
    Cache::Memcached:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
